### ISSUE TITLE
Enhancement: File tree listing

### ISSUE THREAD

**Issue by AndreasSchantl** [kooohei/brackets-synapse#11]
Please remove the up (..) and current (.) folders when opening a folder. These are not needed i order to use the file tree.

**Comment by kooohei** [comment]
these folders, do you see in any folder?

**Comment by AndreasSchantl** [comment]
Yeah! I see them in every folder...
![file-tree](https://cloud.githubusercontent.com/assets/9936988/9625487/ce09766e-5156-11e5-9270-5db3d4c674a2.PNG)

**Comment by kooohei** [comment]
ok try below
open edit server setting panel and then
input "., .." to exclude files.
click "update" button.

**Comment by AndreasSchantl** [comment]
Nice! That helped. Any plans to implement this by default?

**Comment by kooohei** [comment]
ok I will set to default "., .." to next update.
