### ISSUE TITLE
Speed of opening documents.

### ISSUE THREAD

**Issue by munkex** [kooohei/brackets-synapse#14]
Hey,
your plugin is working great, my only consern with it is that the speed at wich it it open files and shows document and files inside a folder is VERY slow (when double clicking to open or show content of file or folder). Just tried to open  a file with 4 lines of code and it took almost 20 seconds, and around same time for a folder to show the content it have inside and im on a fiber connection with 40/40, and when i try do the same in CODA, sublime text so on it opens up instantly.

Is there anyway possible for you to try and see if it possible to improve this?

**Comment by kooohei** [comment]
ok It takes as long as 20 seconds of it is abnormal
do you try other ftp sever? and same problem?

Of course I want fix it. but I could not Reproduction my environment.

but try it
Click "Help" > "Show Extensions Folder" > "user"
to move folders other than the "brackets-synaspe" to the desktop or some place.
and restart brackets.
try synapses connection.

Ill wait for your result.

**Comment by munkex** [comment]
Hey,
Thanks for the reply,

I tried to do what you asked and connected to another FTP server and it worked without delay,
i guess its something on the other FTP server then,

Sorry for troubling you with something that seemed a problem with my own ftp server

**Comment by kooohei** [comment]
I see, but I in the mood, because there is not problem when the coda etc connection to server, right?

**Comment by munkex** [comment]
Theres no problem when connecting with other ikke coda, mabye its because og passive connecting setting, that is available in others
