### ISSUE TITLE
1.1.1 Files are not uploaded

### ISSUE THREAD

**Issue by p33k** [kooohei/brackets-synapse#21]
I use the new 1.1.1 Version (never used the plugin before) with Brackets 1.4 Build 1.4.0-16380.
Login to FTP works, Opening the Files too. But save -> Upload doesn't work. It doesn't upload the file.

Is there an indicator or a console that shows if upload was succesful or not? Like in eqFTP extension which I used before.

**Comment by kooohei** [comment]
sorry late ><
now available 1.1.2, I wish fixed this problem.

**Comment by kooohei** [comment]
I thought too. this ext need indicator for log.
I'll clean up source error handling and build that function.

(but first I have to build switching sort function.><)

Please wait few day.
