### ISSUE TITLE
Error alert doesn't go away

### ISSUE THREAD

**Issue by p33k** [kooohei/brackets-synapse#28]
When an error occurs, for example "ERROR Could not saved file to the server" (which by the way should be "ERROR Could not save file to the server" in correct english), the alert overlay stays forever.

It should be removable with and "X" symbol and go away after a short period of time.

**Comment by kooohei** [comment]
Click to the alert i(t self). maybe there are several rather than one when it still shown
but you right, It is a little strange behavior.

English is the most troublesome enemy for me while born in the country of the same artisans and you.

**Comment by p33k** [comment]
ok there were 8 or so error alerts.
Click to close is ok, but maybe put a X in there for better usability
