### ISSUE TITLE
red box "error code undefined" appears static in the synapse left column 

### ISSUE THREAD

**Issue by holyguard** [kooohei/brackets-synapse#31]
- this issue has been tested in sftp connections in lubuntu 14.04
- after one or two operations with synapse (connect, open file...) a red box appears with message "error code undefined" in the left column and the sftp operations are blocked

- ![untitled](https://cloud.githubusercontent.com/assets/2372290/9837302/d24e14c2-5a3a-11e5-8724-f274bfa6776c.png)

**Comment by kooohei** [comment]
I know , that is bug, error handling has problem. 
I try to fixed asap
but Im working other stuff.
please wait a few days.

thx

**Comment by kooohei** [comment]
please try again after update to 1.2.0.
