### ISSUE TITLE
Unable to Save SFTP Host with Nonstandard Port 

### ISSUE THREAD

**Issue by watsonit** [kooohei/brackets-synapse#32]
When changing the SFTP port from the default 22, the APPEND button enters a disabled state. Trying to trick the UI by entering all information and then changing the port (without exiting the port field) and clicking APPEND does not work.

I found where SynapseDomain.js reads the port from the form and hard-coded to my needed port. This allowed saving of the host. I then found where brackets.json stores the brackets-synapse.server-settings. I reverted my hard-coded port hack and now have the syntax needed for the remote SFTP host definitions. This gets me going for now, but I do believe ports should not be limited to those containing 22.

**Comment by kooohei** [comment]
thanks a lot.
you right, I will try fix to soon.
however, if you know see stored file.
Now, Synapse setting stored by plain text.
I appending crypto function for encrypte to settings.
give me a few time.

**Comment by kooohei** [comment]
please try after update to 1.2.0.
If yet happen some trouble yet please tell me

**Comment by kooohei** [comment]
sorry, not fixed yet.

however 1.2.1 release.
modified all function for the network connection.
please try it.
