### ISSUE TITLE
When i create file on server (throught brackets) and try to edit some exisiting files i get the following 2 errors

### ISSUE THREAD

**Issue by munkex** [kooohei/brackets-synapse#34]
I wont know why exatcly im getting these, but all i have done is logged into my webserver,
i created a index.php (through brackets) and wrote some html in it and i got the following error: Could not save file to server - permission died
(i then disconnect from server and close brackets and start up again, the file is  there but still get same error when trying to write in it)
i then tried to edit a existing file on the server and got the error on the second screenshot.

![skaermbillede 2](https://cloud.githubusercontent.com/assets/2952180/10103325/84a04b2e-63a3-11e5-949b-0fa6d5e5d958.png)
![skaermbillede 3](https://cloud.githubusercontent.com/assets/2952180/10103326/84a3a620-63a3-11e5-91a3-658742284f04.png)

**Comment by munkex** [comment]
Just noticed that i could save files on some servers...

permissions in both folders and on both files are 644.. so it is not a permission error that is making the issue.

**Comment by kooohei** [comment]
1.2.1 release.
modified all function for the network connection.
please try it.
