### ISSUE TITLE
could not save file to server permission denied

### ISSUE THREAD

**Issue by shoaibqadri92** [kooohei/brackets-synapse#37]
Hi,

i got this error when i save file to server "could not save file to server permission denied". 
I changed permission on server directory but still getting same error.

Please help me out asap.

Thank you

**Comment by munkex** [comment]
Hey,
i am having this issue aswell and made a post 6 days ago and still no answer from him

**Comment by kooohei** [comment]
hi sorry late, I made the problem too much update for SFTP connect appended.
Now Im rebuilding to connect methods.
then I will fix to the UI problem (Log)
please wait, I worked.

**Comment by munkex** [comment]
Hey Kooohei.

How is it going with the update on file permissions?

still getting the same error as this guy and the issue post i made earlier: https://github.com/kooohei/brackets-synapse/issues/34

I had hoped the newest release would have fixed this :(
