### ISSUE TITLE
1.2.1 does not work at all

### ISSUE THREAD

**Issue by eduardomart** [kooohei/brackets-synapse#40]
I have tried saving FTP/SFTP settings and all Synapse says is "Authentication Error. Please check setting your input" - All the information I am using is correct.

**Comment by ytessier** [comment]
Hi there - the plugin was working fine prior to 1.2.1 - I authenticate successfully but I don't left hand-side Synapse file browser does not load, so I can't do anything.  That's after I have deleted my servers because I could no longer connect to them.

**Comment by kooohei** [comment]
can you confirm developer tools?
Debug > Show Develper Tools
then
Console (tab) > All

**Comment by ytessier** [comment]
Here's what I see in the dev logs:


[NodeDomain] Error loading domain "synapse": Unable to load one of the
modules:
C:/Users/Yannick/AppData/Roaming/Brackets/extensions/user/brackets-synapse/node/SynapseDomain,
reason: Cannot find module 'jsftp'/utils/NodeDomain.js:148 (anonymous
function)

**Comment by ytessier** [comment]
After submitting my password in the decrypt pop-up I get the following in
the dev console:

 Uncaught TypeError: undefined is not a functionPanel.js:185

(anonymous function)thirdparty.min.js:559 (anonymous
function)thirdparty.min.js:559 jthirdparty.min.js:559
k.fireWiththirdparty.min.js:559 e.(anonymous function)thirdparty.min.js:559
jthirdparty.min.js:559 k.addthirdparty.min.js:559 (anonymous
function)thirdparty.min.js:559 jthirdparty.min.js:559
k.fireWiththirdparty.min.js:559 e.(anonymous function)Notify.js:94
(anonymous function)thirdparty.min.js:559 (anonymous
function)thirdparty.min.js:559 jthirdparty.min.js:559
k.fireWiththirdparty.min.js:560 hthirdparty.min.js:559
jthirdparty.min.js:559 k.fireWiththirdparty.min.js:559
k.firethirdparty.min.js:560 n.extend.dequeuethirdparty.min.js:560
d.completethirdparty.min.js:559 jthirdparty.min.js:559
k.fireWiththirdparty.min.js:560 Xb.ithirdparty.min.js:560 n.fx.tick

**Comment by kooohei** [comment]
ok sorry, fix soon.

**Comment by kooohei** [comment]
1.2.2 upload now.
please try that.

**Comment by ytessier** [comment]
Thanks!

**Comment by ytessier** [comment]
I'll be able to test in an hour or so.

**Comment by ytessier** [comment]
Finally go around to testing 1.2.2 - same error here:

 Uncaught TypeError: undefined is not a functionPanel.js:185

 (anonymous function)thirdparty.min.js:559 (anonymous
function)thirdparty.min.js:559 jthirdparty.min.js:559
k.fireWiththirdparty.min.js:559 e.(anonymous function)thirdparty.min.js:559
jthirdparty.min.js:559 k.addthirdparty.min.js:559 (anonymous
function)thirdparty.min.js:559 jthirdparty.min.js:559
k.fireWiththirdparty.min.js:559 e.(anonymous function)Notify.js:94
(anonymous function)thirdparty.min.js:559 (anonymous
function)thirdparty.min.js:559 jthirdparty.min.js:559
k.fireWiththirdparty.min.js:560 hthirdparty.min.js:559
jthirdparty.min.js:559 k.fireWiththirdparty.min.js:559
k.firethirdparty.min.js:560 n.extend.dequeuethirdparty.min.js:560
d.completethirdparty.min.js:559 jthirdparty.min.js:559
k.fireWiththirdparty.min.js:560 Xb.ithirdparty.min.js:560 n.fx.tick

**Comment by ytessier** [comment]
What's interesting is that after I've removed the extension and re-installed it, it remembers my crypto password and does not ask me to create a new one.

**Comment by Icemains** [comment]
yeah. i get the same. and it wont acept the password i mae previously

**Comment by kooohei** [comment]
now 1.2.2 available, and functionPanel.js is no relationship with synapse.

**Comment by kooohei** [comment]
perhaps other extension make conflict.
can you tell me installed extensions?

**Comment by kooohei** [comment]
What's interesting is that after I've removed the extension and re-installed it, it remembers my crypto password and does not ask me to create a new one.

this is no problem, extensions config write to .brackets.json 
please confirm [Debug] -> [Open Preferences File]
you can find the line with brackets-synapse prefix.

**Comment by ytessier** [comment]
I removed all other extensions and re-installed brackets-synapse and after
adding my password here's the error I get in the console:

Uncaught TypeError: undefined is not a function
/C:/Users/Yannick/AppData/Roaming/Brackets/extensions/user/brackets-synapse/modules/Panel.js:185

**Comment by kooohei** [comment]
ok thanks, I wanted it.
please try 1.2.3, now available.

**Comment by ytessier** [comment]
OK - it's working again

**Comment by ytessier** [comment]
Thank you! Very useful extension.

**Comment by kooohei** [comment]
thanks too.
This extension does not improve.
If you do not have everyone's advice.

**Comment by ytessier** [comment]
I agree.  Here's an error I'm getting now when saving a file.

Uncaught Error: Could not save file to server<br>     /FileManager.js:99

I know I can update my AWS ec2 instance using winSCP on port 22
successfully using the same user.  Actually, I can auto upload to my AWS
server using JetBrains PHPStorm as well using the same user, etc.

**Comment by kooohei** [comment]
ok so, did file actually saved?

**Comment by kooohei** [comment]
I need help you, 
open the file FileManager.js ([Help] ->[Show Extensions Folder])
user -> brackets-synapse -> modules -> FileManager.js

and replace the following code and 99 line.

throw new Error("Could not save file to server", err);

then please tell me what did you see on the error log when retry same action.(file save)

**Comment by ytessier** [comment]
Uncaught Error: Could not save file to server FileManager.js:99 
(anonymous function) thirdparty.min.js:559 
(anonymous function) thirdparty.min.js:559 
j thirdparty.min.js:559 
k.fireWith  thirdparty.min.js:559 
e.(anonymous function) RemoteManager.js:194 
(anonymous function)  thirdparty.min.js:559 
(anonymous function)   thirdparty.min.js:559 
j   thirdparty.min.js:559 
k.fireWith    thirdparty.min.js:559 
NodeConnection._receive  /utils/NodeConnection.js:498

**Comment by kooohei** [comment]
sorry for the late response.
please confirm error in the developer tools after update to version 1.2.7

**Comment by kooohei** [comment]
now available 1.2.71.
append to the display response code with error on synapse console.
please confirm the number of code.
