### ISSUE TITLE
password

### ISSUE THREAD

**Issue by Icemains** [kooohei/brackets-synapse#41]
I made a password whitch worked for a few days and after the update in wont work anymore... 
what to do?

**Comment by kooohei** [comment]
I want to hear a little more in detail.
can you show the dialog for decrypt password when launced synapse?

**Comment by Icemains** [comment]
it wont come up again. i tried to uninstall and re install and now it just wont show..

**Comment by Icemains** [comment]
i looked in my 'brackets.json file' and couldnt fint tha prefix you mentioned.? is there perhaps something thats missing

**Comment by kooohei** [comment]
"brackets-synapse.version"
"brackets-synapse.server-settings"
"brackets-synapse.use-crypto"
adove properties must there in brackets.json.

so please tell me do you have problem after reinstall.
the problem, password is not valid after extension update. right?
