### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by mightymaxv2** [kooohei/brackets-synapse#42]
The error is "Uncaught Error: Could not save file to server&lt;br&gt;" when I try to save files. I don't get the little red error banner, I have to open debug tools to see it. 

File that throws the error is modules/FileManager.js ln 99.

Using sftp, port 22, private key with passphrase

I started using the plugin at 1.1, and have never been able to upload.

Thanks for your help!

**Comment by kooohei** [comment]
sorry late.
however I have been ready new version, but could not upload to extension registry...

**Comment by kooohei** [comment]
and please tell me, sftp connection is not exists at 1.1.
did you never connected to server via the FTP before version 1.2?

**Comment by mightymaxv2** [comment]
I connected, but couldn't upload anything.  The red banner quit appearing
when I upgraded to 1.2

**Comment by kooohei** [comment]
ok, please confirm to the error in the developer tools after update to version 1.2.7

**Comment by mightymaxv2** [comment]
![capture3](https://cloud.githubusercontent.com/assets/12142246/10432676/ffb1d99e-70c9-11e5-91d8-0691ef423ad8.PNG)
The error is still there.

**Comment by kooohei** [comment]
now available version 1.2.71.
that will be show error with response code.

you will get the number of response code when error occured on Synapse's console.
please tell me the number of code.

**Comment by mightymaxv2** [comment]
It was response code 2. 

The other open issues are related to this one, I believe. Something you said about the remote path made me test something out. I noticed in the console that it was trying to upload to a relative path. I deleted my remote path from my server settings, and went in to the file the long way, and was able to upload. 

So it looks like your downloading from the full path, but I don't think you're using the full path to upload.

I have to compliment you on your plugin, though. Even if it's not quite working, I'm really impressed with it!

**Comment by kooohei** [comment]
yea sure, the path, It was the rest of the one of the alleged.
synapse convert path for local to remote.
that will there was a problem. thx.

I'll fix it.

**Comment by kooohei** [comment]
oops, there is bug when edit to server setting,
I have to fix first.

**Comment by mightymaxv2** [comment]
This has been fixed. Thank you!

**Comment by kooohei** [comment]
realy!?
thanks for your help!
