### ISSUE TITLE
Files does not upload after save

### ISSUE THREAD

**Issue by MGraversen** [kooohei/brackets-synapse#43]
Hi

I'm new to both Brackets and your extension. It looks like everything works as it should. I can create folders and files on my FTP via Brackets. Only problem is, whenever I edit an existing file and I save it, it doesn't update/overwrite the file on the server. The same goes for renaming existing folders/files.

I'm using:
Regular FTP without SSL
Brackets Release 1.4 build 1.4.0-16380 (release 273804eb3) 
Brackets Synapse 1.2.3

**Comment by jimstamper** [comment]
I'm having this same issue with release 1.2.3.

**Comment by kooohei** [comment]
sorry late and thanks for the report.
I have been ready new version, but could not upload to extension registry

**Comment by MGraversen** [comment]
Hi kooohei

Can I download the files from github and then install/copy them manually into Brackets?

**Comment by kooohei** [comment]
yea sure, download the zip file to extension folder from github  then execute "npm install" in the brackets-synapse/ and brackets-synapse/node folder.

**Comment by tiger2380** [comment]
My edited files are being uploaded but they are uploaded to my root folder on my server. How can I change the location?

**Comment by realmchat** [comment]
same problem with upload, files only saved lokal...

**Comment by MGraversen** [comment]
![ss_brackets_ftp_error](https://cloud.githubusercontent.com/assets/15054569/10429788/5d12638e-70fb-11e5-81e5-91d9721e3a73.png)

Still doesn't work, but know I get an error telling me that it doesn't work :(

**Comment by kooohei** [comment]
ok please confirm  "Debug" > "Show Extension Folder" > "user" > "brackets-synapse" > "error.log"
is there the error of your problem?

**Comment by kooohei** [comment]
error.log is exists over the version 1.2.5

**Comment by MGraversen** [comment]
The errorlog file is empty. I have testet it on 3 different PC's and now on to different hosts, same problem every time :(

**Comment by kooohei** [comment]
i see. so no error in develop tools too?

**Comment by MGraversen** [comment]
Not really sure how to check developer tools. I had "/web/folder".
I tried removing input in CURRENT DIRECTORY, but the extension didn't save my changed settings.

**Comment by kooohei** [comment]
ah sorry, that in the Brackets menu.
[Debug] -> [Show Developer Tools] -> [Console] -> [All or error]

**Comment by realmchat** [comment]
i have a file .remotesettings in my local project folder where protocol ans remotepath is empty. (... ,"protocol":"","port":21,...    ..."remotepath":"","uploadOnSave":true}). is this file created by synapse?

**Comment by realmchat** [comment]
the synapse console says index.php have been uploaded successfully, the error console shows no error and synapse error log is empty...

**Comment by kooohei** [comment]
.remotesettings is not related to synapse.

**Comment by MGraversen** [comment]
![ss_brackets_ftp_error02](https://cloud.githubusercontent.com/assets/15054569/10447022/d21dfa82-7180-11e5-9040-d0dda6afc2be.png)

Can this help?

**Comment by kooohei** [comment]
plz update to 1.2.71

**Comment by MGraversen** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/15054569/10448154/1e0d24c2-718b-11e5-8851-b9cce82b1e12.png)

Still no success :(

**Comment by kooohei** [comment]
error code 553.
write permissions of the file or the base directory of the files do you have??

**Comment by MGraversen** [comment]
I tried 664 and 775 on each above directory and the file. I can edit the file via Filezilla and via WordPress' backend editor.

**Comment by kooohei** [comment]
oh, i see.
ok please wait.

**Comment by kooohei** [comment]
ok now available 1.2.72
that will be display upload file path instead of filename to console.
please check it whether path is right or not.

**Comment by MGraversen** [comment]
In-app update of extension doesn't work, and the one I download fra github is 1.2.71.

**Comment by kooohei** [comment]
Realy sorry,I have to go few hour.
I will fix this issue when I back.

**Comment by MGraversen** [comment]
No problem. Looking forward to it ;)

**Comment by realmchat** [comment]
Hi there, 
found a workaround... Seems the Problem is with the serverpath.
With ./ and navigate to folder manually works fine for me. But with /subfolder the file is not saved.

**Comment by kooohei** [comment]
Hi
serverpath, did you mean the current directory in the server settings?

**Comment by realmchat** [comment]
yes, the directory path. By the way you've done great work with this extension.

**Comment by kooohei** [comment]
sorry for the late.
I work up to now back from there to the home.
I pray that it has been improved a little.

**Comment by MGraversen** [comment]
V 1.2.81 still gets the same error and now I need to input a folder in CURRENT DIRECTORY, not that that is a problem in itself. :(

**Comment by kooohei** [comment]
I modified related to path problem.
now uploaded.
It will be show you actual paths for local and remote when occuer the upload error .
please try it.

**Comment by MGraversen** [comment]
It freaking works! This is so great. Brackets just became my favorite HTML/CSS-editing tool thanks to your extension! :D Thank you so much!

**Comment by kooohei** [comment]
great! 
It was a little peace of mind.
but I think that far yet stable.
please cooperate and if something also.

**Comment by MGraversen** [comment]
Sure I will let you know, if I notice any other bugs. But for me your plugin is what makes Brackets usable ;)

**Comment by kooohei** [comment]
thanks for the help.
It does not make sense unless Could use to everyone.
First of all so that it can respond to various requests so that you become a stable operation.

**Comment by realmchat** [comment]
still does not work with directory path, but thats not a problem at all. Is there a way to make a donation for your great plugin? Some frinds and me would like to send you some bucks... A paypal address or something?

**Comment by kooohei** [comment]
wow thanks so much but I can not receive it.

Also we would like to share information in the future.
Sincerely thank to its favor.

And I will fix :D

**Comment by sameh0** [comment]
the upload doesn't work , and it  i don't get any error when trying to upload both on Developer tools or on the Synapse Console , my account has a full read&write  permissions , any ideas ??? 
using brackets latest & Synapse latest & OS X 10.11 .

**Comment by kooohei** [comment]
hi, can you confirm ftp server log?
Is protcol a FTP?

**Comment by kooohei** [comment]
sorry i fixed. the online status, it has not been changed.
now update to 1.2.84.

**Comment by sameh0** [comment]
yup it's FTP , and i'll update

**Comment by sameh0** [comment]
And YES it's working , Thank you very much this will help me achieve many goals faster .
Have a nice day buddy .

**Comment by kooohei** [comment]
thanks for the reported.

This problem was lucky because was able to predict that it is the location that you modify the other day.
Such morning is 3:00.XD
