### ISSUE TITLE
Upload problem

### ISSUE THREAD

**Issue by kooohei** [kooohei/brackets-synapse#45]
Thanks for the feedback of problem.
And I'm sorry could not fix to problem yet.

So, I have a request.
I'm happy and give me a report with protocol(FTP or SFTP)
Whether was confirmed permission, chroot.
Especially, chroot, it is troublesome in FTP.
If file not saved, please confirm chroot list whether that was contain the error occured context.

and confirm of error methods.
- [Debug] -> [Show Developer Tools] then choose "Console" tab and click "All".
- [Help] -> [Show Extension Folder] -> [user] -> [brackets-synapse] -> [error.log]

please confirm to above method.

**Comment by anabarasan** [comment]
The upload of the file still fails.

**protocol** : SFTP

There are no errors in the Developer Tools Console.  But the message appears in the **synapse console**.  it says **... upload to server failed. [Response Code: 2]**

I am unable to upload the **_error.log_** file, here at work, so pasting the contents of the file here. 

I added the dash at the beginning of the lines so that the contents appear here in the comment

BEGIN:  error.log

-[0]:0
-[0]:0
-[0]:0

END: error.log

![synapse error](https://cloud.githubusercontent.com/assets/1195250/10448166/854c7418-71a8-11e5-92b4-3662268c4591.png)

**Comment by kooohei** [comment]
please confirm path on the synapse console at error occered after updae to 1.2.72

that was displayed just the filename, this version will show you the path from your current directory.

**Comment by anabarasan** [comment]
i am not able to connect to the server after 1.2.72 update

**Comment by anabarasan** [comment]
I updated to 1.2.73 now, and tried to save / upload the file.  

Still upload is failing

The error.log is empty, and there are no errors in the developer console, when trying to save / upload.

![synapse error](https://cloud.githubusercontent.com/assets/1195250/10475078/dab49e9e-725c-11e5-928a-7b5da231e900.png)


The errors in the screen shot appeared before attempting to upload.

**Comment by kooohei** [comment]
sorry for the toooo late.
now available ver 1.2.80

Though I think that it has become a little to better more than 1.2.7x

**Comment by anabarasan** [comment]
find the error log

```
[2015/10/14 14:39:46]:{"message":"Failed to upload to the server.(static/js/content/view.js)<br>[Response Code:2]","datetime":"2015/10/14 14:39:46","error":{"code":2,"lang":"","opt":{"localPath":"C:/Users/agangada.AP01/AppData/Roaming/Brackets/extensions/user/brackets-synapse/__PROJ__/xxx.xxx.xxx.xxxxxxx.com_xxx.xxx.xxx.xxxxxxx.com_uuuuuuuu/20151014143851/static/js/content/view.js","remotePath":"static/js/content/view.js"}}}
```


![synapse error](https://cloud.githubusercontent.com/assets/1195250/10479497/65cc5f10-7282-11e5-8076-6c37c74a27de.png)

**Comment by kooohei** [comment]
did you entered the value to the CURRENT DIRECTORY on Server Setting panel?

**Comment by kooohei** [comment]
if you entered value "/xxx" to CURRENT DIRECTORY.
please try once enter instead of "./"

**Comment by anabarasan** [comment]
I have given CURRENT DIRECTORY value as the folder containing the files
/home/<userid>/projects/<project name>

**Comment by kooohei** [comment]
sorry I found the problem about symlink paths at just a sftp connection.
upload now available 1.2.81

I wish it will fix your problem ><

**Comment by kooohei** [comment]
oops if your entered /home/---, that weird path you wrote the error log

**Comment by anabarasan** [comment]
yes the remote path which was there in the error log seems to be like relative url

the entire url should be something like
```
/home/<userid>/projects/project/static/js/content/xxxx-view.js
```

**Comment by kooohei** [comment]
I will investigate that

**Comment by anabarasan** [comment]
I tried it with the new **1.2.81** update. 
still facing the same issue

```
[2015/10/14 16:26:25]:{"message":"Failed to upload to the server.(static/js/content/docroot-view.js)","datetime":"2015/10/14 16:26:25","error":{"level":"client-timeout","opt":{"localPath":"C:/Users/agangada.AP01/AppData/Roaming/Brackets/extensions/user/brackets-synapse/__PROJ__/xxx.xxx.xxx.xxxxxx.com_xxx.xxx.xxx.xxxxxxx.com_agangada/20151014162522/static/js/content/xxxxx-view.js","remotePath":"static/js/content/xxxxx-view.js"}}}
```
In console there is a message saying 

```
Uncaught TypeError: Cannot read property 'type' of null
```

pointing to file FileTreeView.js:496

![synapse error](https://cloud.githubusercontent.com/assets/1195250/10481836/214673c6-7291-11e5-9db8-ae8f29e76920.png)


![synapse error](https://cloud.githubusercontent.com/assets/1195250/10481853/421241c0-7291-11e5-8aa8-e89a80c73231.png)

**Comment by kooohei** [comment]
yes I understood problem, but that is not actual problem.
just little bit a problem after failed to upload the file.

now uploaded new version.
the ext use 2 upload function.
it is when the file saved and create new file.
I fixed you gave me the error log with weired mismatch path
and It will be show you the extend error detail when error occured.
In particular, actual path for upload command.

I'm sorry the problem without advancing any

**Comment by anabarasan** [comment]
Awesome.
Thanks kooohei.
Now upload is working.
