### ISSUE TITLE
using FTP files do not show

### ISSUE THREAD

**Issue by cjeller** [kooohei/brackets-synapse#47]
Created files do not show in directory on disconnect and reconnect.

**Comment by kooohei** [comment]
i need more details.
server setting (with out account), what did displayed on ext's console, developer tools

**Comment by cjeller** [comment]
It happens when trying any ftp connection. The system will not display any
files previously on the server.

Server: from.sitename.com
User:name@sitename.com
Port:21
(Basic standard settings)

Only the setting file shows and it's empty. You can create a new file and
it will save to the server, but no files will show from the server.


On Oct 12, 2015, at 11:22 PM, Kohei Hayashi <notifications@github.com>
wrote:

i need more details.
server setting (with out account), what did displayed on ext's console,
developer tools

—
Reply to this email directly or view it on GitHub
<https://github.com/kooohei/brackets-synapse/issues/47#issuecomment-147616964>
.

**Comment by kooohei** [comment]
i see, can you try reconnect with the server setting enter the empty?

**Comment by kooohei** [comment]
What now then?

The issue close once, but also please visit at any time if there is a problem.

**Comment by danvim** [comment]
@kooohei I have the same problem. I used all the same settings in FileZilla, but in Synapse Console, it said found 21 files but never shown the file tree and the brackets loading animation just keeps on playing.

Settings in FileZilla(in case I didn't entered them correctly in Synapse):
Host: www.example.com
Port: (empty)
Protocol: FTP
Encryption: Use explicit FTP over TLS if available
I have my username and password.
