### ISSUE TITLE
unable to connect to server

### ISSUE THREAD

**Issue by anabarasan** [kooohei/brackets-synapse#48]
I just upgraded to 1.2.72  and after that i am unable to connect to server.

Synapse Console says **Failed to open the project**

and **error.log** file is empty.

![synapse unable to connect](https://cloud.githubusercontent.com/assets/1195250/10448945/f5e8c4a6-71ad-11e5-8224-d2c22b171f9a.png)

**Comment by anabarasan** [comment]
protocol : SFTP
port : 22
passphrase authentication

I am able to connect & edit files with notepad++, so no connectivity issues there.

**Comment by kooohei** [comment]
thx for detail info.I understood my mistake on export error funcs thunks.
plz tell me could you connected to the server via the sftp before updated?

**Comment by anabarasan** [comment]
before updating i was able to connect and view files
but was not able to upload.

**Comment by kooohei** [comment]
do you remember the version before update?

**Comment by anabarasan** [comment]
it was 1.2.71

**Comment by kooohei** [comment]
sorry one more question.
you said use passphrase.

Is the passphrase for it is key authentication?
or
did you choose password authentication via the SFTP?

**Comment by kooohei** [comment]
and now 1.2.73 available.
please try again.
and please confirm error log when the error occured.

**Comment by anabarasan** [comment]
I am using password authentication for SFTP.

still unable to upload the file on save.

The error.log file is empty

![synapse error](https://cloud.githubusercontent.com/assets/1195250/10475049/6a94d75a-725c-11e5-9085-0f5c84da5b34.png)
