### ISSUE TITLE
No Scroll when you have too many working file

### ISSUE THREAD

**Issue by puneethrai** [kooohei/brackets-synapse#50]
To Reproduce: Open too many working file (Depends on screen size) -> Now open Synapse -> If you have multiple server configured then you can't navigate/connect to your last server 

To fix: In style.css -> #synapse-server-list -> change height:auto to height:100%

**Comment by kooohei** [comment]
ok 
Surprisingly to many of the same questions I am surprised
I will added scrollbar to that soon

**Comment by puneethrai** [comment]
Thanks

**Comment by kooohei** [comment]
Sorry for the late.
I was puzzled to consistency in each platform.
now ver 1.2.83 for fixed scroll problem.
please try it.

**Comment by puneethrai** [comment]
Hey I updated to latest version i.e., 1.2.84 . Still I'm not able to scroll. I'm using windows 7 pc.

**Comment by kooohei** [comment]
https://kooohei.github.io/screen.png

The server list height fixed more than a predetermined length.
display scrollbar when mouse over to the list.

**Comment by puneethrai** [comment]
The issue occurs when server list is rendered by default i.e., by not toggling open server list button  and you have lot of working files

**Comment by kooohei** [comment]
ok I updated.
however, the list opened by the launch when only first launched.

If for example, the necessary change project in the middle we have editing server setting,
we must close the synapse once.
The next time we open it, because to be able to resume from the middle of the set.

**Comment by kooohei** [comment]
oops sorry idk,
"The issue occurs when server list is rendered by default"
The synapse is not opened when the ext launched before update this version.

**Comment by kooohei** [comment]
and if I could not see treeview by have too many server listed, just close the server list.

**Comment by kooohei** [comment]
I'm sorry. It seems to have been a response to the different problems....

so Issue is the could not scroll in the server list when the brackets's working set panel had too may files.  right?

**Comment by kooohei** [comment]
Could you in the situation a screen shot at the time of occurrence of the problem?

**Comment by puneethrai** [comment]
![synapse_github](https://cloud.githubusercontent.com/assets/1643479/10581900/95e9d5f0-76a2-11e5-8a4d-d2e026536d94.png)

I'm not able to reproduce the no scroll on server list because by default all my server list are hidden . But in the image provided When adding new server I don't get scroll so it is very difficult to add a new server with too many working file opened

**Comment by kooohei** [comment]
sorry for the late.
I have a new version ready.
but It could not upload to the extension registry,
because now, registry server is down.
I will upload the new version when the reg server relaunch.

**Comment by kooohei** [comment]
the new version 1.2.86, It can toggle show the working files panel
