### ISSUE TITLE
Server List scrollbar

### ISSUE THREAD

**Issue by andreassoegaard** [kooohei/brackets-synapse#51]
Since I got more than 10 clients I wanted to add them all to synapse so that I can quickly edit in their files directly on their server. But I have now added more than 10 servers/FTP's and realized I can't scroll in the server list? So how can I connect to the servers at the bottom?

**Comment by andreassoegaard** [comment]
Fixed:

1. Go to Help -> Show Extensions Folder
2. Go to \user\brackets-synapse\ui\css
3. Open style.css and edit #synapse-server-list
4. Change height: auto; to height: 90%;

Also credit to https://github.com/kooohei/brackets-synapse/issues/50

**Comment by kooohei** [comment]
i see, 
I was unexpected scroll on server list
I will add to that soon

**Comment by kooohei** [comment]
Sorry I made you wait.
now available ver 1.2.83 for fixed scroll problem.
please try it, and thanks for the report.
