### ISSUE TITLE
Save on upload

### ISSUE THREAD

**Issue by mightymaxv2** [kooohei/brackets-synapse#52]
Save on upload quit working with new update to 1.2.83. Tested with current directory set to root ("/"), and user's path ("/home/username/"). Fails silently, meaning no errors in synapse console or brackets console.

**Comment by kooohei** [comment]
I was tried connected to root directory ("/") and home directory ("/home/xxxxx"). it was success.
If the your use account for FTP(?) have been set chroot by the ftp server.
It might be that way.
Can you confirm your ftp server log?

**Comment by kooohei** [comment]
Is it possible to try at the time of the new addition?

**Comment by kooohei** [comment]
sorry i fixed. the online status, it has not been changed.
now update to 1.2.84.

**Comment by Komoszek** [comment]
For me, uploading is now working.

**Comment by mightymaxv2** [comment]
Uploading is working again with the new update. Thank you. 
Also, sorry I was not responding... Sleeping. :)
