### ISSUE TITLE
Server list not shown when Bracket is launched

### ISSUE THREAD

**Issue by puneethrai** [kooohei/brackets-synapse#53]
To reproduce: Install synapse and don't set any password ->  Add few servers to synapse -> connect to those server -> work on any files -> close synapse -> close Bracket -> open Bracket -> open synapse -> prompts for new password click on "Later" -> Now on the synapse server list shows nothing -> When I add new server then I can see all my servers.

Let me know if you need any debugging help. It is always reproducible in my machine

**Comment by kooohei** [comment]
The synapse as It is normal behavior.
1. launch Brackets.
2. launch Synapse.
3. open server list.
4. connect to server.
5. brackets will open the remote current directory to project.
(Before connecting to server, Synapse will store the current project to inside temporary memory.)

sorry I confusing.
Your request is the server list must opened when launch the synapse. right?

**Comment by kooohei** [comment]
Synapse will not open the server when launched.
Did you click to open the server list by server list button?

**Comment by kooohei** [comment]
or does this mean it is the contents of the server list that opened was empty?

**Comment by puneethrai** [comment]
Oh OK..when I click open the server then it is opening...But by default when I open Bracket and then Synapse...It should list all my servers right

**Comment by kooohei** [comment]
Of course I can it.
But certainly before, there was a request that had been worrying about the string to be listed,
Perhaps it is I think for security.
It was resolved to be able to give any name to each setting.
then I was changed to that is closed when the launched.
anyway, I think same things your plan.
Once you try the plan, consider if there is a problem.
please wait few minutes.

**Comment by kooohei** [comment]
or Here! I was confused with different Issue.

ok I updated.
however, the list opened by the launch when only first launched.

If for example, the necessary change project in the middle we have editing server setting,
we must close the synapse once.
The next time we open it, because to be able to resume from the middle of the set.

**Comment by puneethrai** [comment]
This issue is not happening in 1.2.85 . So closing this issue.
