### ISSUE TITLE
Unable to open files

### ISSUE THREAD

**Issue by Otradny** [kooohei/brackets-synapse#54]
Hi!

When i'm clicking on file to open it - nothing happens.

OS: ElementaryOS Freya (64-bit) (Built on Ubuntu 14.04)
Brackets: 1.5.0-16538 (release cf9cf4698) 
Brackets-Synapse: 1.2.86

**Comment by kooohei** [comment]
hi, now I'm knew elementaryOS first time. looks good.
so did you use my extension before this version ?

**Comment by Otradny** [comment]
Nope. Using brackets and synapse on elementary first time.
On windows 10 - everything is good.

**Comment by Otradny** [comment]
I thought - there is conflict with other extensions, so i disabled everything except synapse - still nothing.

**Comment by kooohei** [comment]
ic, ok perhaps it is not related this issue, now 1.2.86 available.
please try it.

and, what did development tool told you when the file icon clicked?

**Comment by Otradny** [comment]
![screenshot from 2015-10-22 15 12 05](https://cloud.githubusercontent.com/assets/15246656/10664845/5bc268e0-78cf-11e5-972c-3e053f686ad6.png)

Still nothing :(

**Comment by kooohei** [comment]
It seems like no problem, ok.
see menus [Debug] -> [Show Developer Tools] then open the developer tools.
click the "Console" tab on top of the window.
so you can retrieve something about synapse.

**Comment by Otradny** [comment]
unfortunately I can't  open Developer Tools too))) by clicking on it - nothing, press f12 - nothing)))) 

its likely to have go back to windows :(

**Comment by kooohei** [comment]
ok, now i'm installing elementaryOS.
I'll investigate to this issue.

however, that OS looks like that has ubuntu to base, although, you know,
Brackets is not support this.

**Comment by Otradny** [comment]
However it would be cool if it worked. Thanks for help!

**Comment by kooohei** [comment]
Thanks!
I'll tell you if I find a problem.

**Comment by Otradny** [comment]
okey ,will be waiting

**Comment by kooohei** [comment]
sorry for the late.
I could not reproduced this issue, 
ElementaryOS Freya + VirtualBox on Windows 10

Synapse has connected to server and No problem about the editing.

**Comment by Otradny** [comment]
Thank you for trying to help. It seems that the problem in my current configuration... maybe hardware or something. Anyway, thanks.

**Comment by kooohei** [comment]
your welcome.
