### ISSUE TITLE
Unable to edit text fields

### ISSUE THREAD

**Issue by lukaswelinder** [kooohei/brackets-synapse#55]
Can't edit text fields when prompted to create a password, creating a directory, or creating a file.

**Comment by lukaswelinder** [comment]
Sorry for the delayed response @kooohei 

Some fields have started working(authentication fields for user and pass). However, when I create a folder of a file, the only key that does anything is the delete key, so I end up creating blank documents.

At present it has rendered the plugin unusable. Any suggestions would be appreciated. Other than this issue, it's a great extension, and I look forward to getting it working.

**Comment by kooohei** [comment]
ic, ok, however there is not many issues about the Form UI anymore
Can you see the screen shot?
parhups I would not reproduce that.

thanks:-)

**Comment by lukaswelinder** [comment]
@kooohei 

I've done a lot of experimenting to reproduce the issue and have found that it is not an issue with synapse, but rather brackets itself, so this issue can be closed. When there isn't an open document in the workspace, text-fields cannot be written to.

I'll take this moment to thank you for your work on Synapse, it's a very handy tool.
