### ISSUE TITLE
can't append anyone sftp server

### ISSUE THREAD

**Issue by limux** [kooohei/brackets-synapse#60]
When append a sftp will issue the error of failed to authenciation, In fact, connet to the host by ssh is ok.
I try 3~4 hosts with same error.

**Comment by kooohei** [comment]
did you confirm the ssh connection?
Is it server log?

**Comment by limux** [comment]
Server listening on :: port 22.
Oct 29 16:34:32 fb_fyoa sshd[571]: Server listening on 0.0.0.0 port 22.
Oct 29 16:42:11 fb_fyoa sshd[640]: Connection from 172.31.1.20 port 58316 on 10.10.1.43 port 22
Oct 29 16:42:20 fb_fyoa sshd[640]: Accepted password for limux from 172.31.1.20 port 58316 ssh2
Oct 29 16:42:20 fb_fyoa sshd[640]: User child is on pid 642
Oct 29 16:42:20 fb_fyoa sshd[642]: Starting session: shell on pts/0 for limux from 172.31.1.20 port 58316

This is server log when connection use ssh.

**Comment by limux** [comment]
![1](https://cloud.githubusercontent.com/assets/110582/10813943/69125698-7e5d-11e5-9fcb-ee4882a01edc.png)

This is connection to 10.10.1.43 by Brackets.

**Comment by kooohei** [comment]
ah ic, that problem is not connection. error message wrong.
Synapse got file list on the current directory after connected to the server.
perhaps, error occured when requested LIST command to the server.
The error log It is not something that lasts?
like a "error occured when read the directory"

**Comment by limux** [comment]
After restart Brackets with do nothing, and set the synapse to connection at once, then there will reports one info of "Initialized completed successfully" and one error of "failed to authentication, please confirm your server setting." and one error of "failed to authentication, please confirm your account setting."
That's all.

**Comment by kooohei** [comment]
I see, so please tell me the synapse's version?
and the developer tools said  what?

**Comment by limux** [comment]
the latest 1.2.87

**Comment by kooohei** [comment]
now 1.2.88
but the version on top of the ext panel, that will change when reboot brackets after update

**Comment by limux** [comment]
That issue perhaps is the bug of brackets. May be I missed some very importent messages to comment.
I made a try on the mac, thers is no this issue. the Synapse connetted to the sftp server successfully. In another word, the issue is only found on win or exactly win7.
Look at the following picture:
 
![1](https://cloud.githubusercontent.com/assets/110582/10837766/3bcbc304-7ef8-11e5-9712-bd6d9191a5de.png)

**Comment by limux** [comment]
Great to your so fast fix and the very nice Synapse.

**Comment by kooohei** [comment]
Thx for the feedback.
hmm I see, I'll try for reproduce on Win7.
So, if that occurred some error again.
please visit here. thx.
