### ISSUE TITLE
Extension Error

### ISSUE THREAD

**Issue by dwaynegardner** [kooohei/brackets-synapse#67]
Updated to version 1.2.90 when the prompt let me know there was an update. Once it had finished updating the extension hasn't worked since. I can't uninstall the extension through Brackets. I'm on Windows 10 64 bit.

Developer Tools error shows:

```
 GET file:///C:/Users/Dwayne/AppData/Roaming/Brackets/extensions/user/brackets-synapse/main.js net::ERR_FILE_NOT_FOUND
ErrorNotification.js:125 [Extension] failed to load C:/Users/Dwayne/AppData/Roaming/Brackets/extensions/user/brackets-synapse - Module does not exist: file:///C:/Users/Dwayne/AppData/Roaming/Brackets/extensions/user/brackets-synapse/main.js
/
```

UPDATE: Manually removed the synapse folder from the extensions folder to try to install an older version. Reinstalled the latest version and it seems to work now so possibly an issue only when upgrading.

**Comment by kooohei** [comment]
Now Im trying reinstall ext on same environment (win10(64bit))
I could not reproduction that.
plz try following steps.

Delete Synapse.
%HOME%\AppData\Roaming\Brackets\extensions\user\brackets-synapse

Disable other extensions.
%HOME%\AppData\Roaming\Brackets\extensions\user\(all folders) to
%HOME%\AppData\Roaming\Brackets\extensions\disable\

Relaunch Brackets.

Reinstall Synapse.

and please tell me, what developer tools said.

**Comment by dwaynegardner** [comment]
Installs and woks fine now after deleting Synapse. Only message regarding synapse in developer tools is:

```
 Recursive tests with the same id are not supported. Timer id: [reent 1] readAsText:	C:/Users/Dwayne/AppData/Roaming/Brackets/extensions/user/brackets-synapse/package.json
```

**Comment by kooohei** [comment]
ok perhups synapse is incompatible with other ext.
but I dont have any idea.

and the error message, are you open the package.json of the synapse before relaunch brackets?
perhups there is no message after relaunch brakets.
try above.

**Comment by dwaynegardner** [comment]
Yes. Restarting once more removed the error message. No more issues. Thank you!

**Comment by kooohei** [comment]
You are welcome
