### ISSUE TITLE
Fake folders appearing in folder history drop-down

### ISSUE THREAD

**Issue by magnetas** [kooohei/brackets-synapse#71]
Hi. After Using Synapse for several times I noticed that when I leave Synapse some new strange folders are added to my "recent folders drop-down".

It looks like they're named after session date+time and are located under synapse extension dir.
Here's an example from my macosx: /Users/magnetas/Library/Application Support/Brackets/extensions/user/brackets-synapse/\__PROJ__/some_conection_details/20151104223612

Unfortunately I get a "Error Loading Prohject" eror when I try selecting one of them. And they push my local directories out of this dropdown.

Any way to avoid these dirs from appearing there?

Thank you

**Comment by kooohei** [comment]
that is normal from ver 1.0
synapse will stored the all edited files every connection for backup. max count is 5.
that folder used by brackets between the synapse connected to server and closed
if ext force quit when connected to server, ext could not remove from recent.

**Comment by kooohei** [comment]
impotant, that is only saved files.

**Comment by magnetas** [comment]
Any ideas how can I get rid of those dirs? if I disconnect from synapse and then close it the directories should not appear?

**Comment by kooohei** [comment]
yes, that is the temporary dirs defferent word.
typically synapse will hope the disconnect from the server before quit the brackets.
connected to the same setting over the 5 times, overwrite to new one.

**Comment by kooohei** [comment]
however If you can see that and removed, no problem
