### ISSUE TITLE
is that possible to sync all remote locally 

### ISSUE THREAD

**Issue by NikosEfthias** [kooohei/brackets-synapse#81]
is that possible to sync all remote locally   for example before a trip to sync all site and when i get internet again upload changes syncing local and remote

**Comment by kooohei** [comment]
ah ic, yea sure, however ftp is multi user server.
this mean, idk who edit to the file.
if that happen, then local and remote file is not much.

yea I know, "the server used by only me", 
I will try, this function append to the extention asap,
but first I have must thing, major update.

plz wait.
