### ISSUE TITLE
Settings must have been crypto before synapse is activated.

### ISSUE THREAD

**Issue by techyogii** [kooohei/brackets-synapse#95]
My connection was working fine. But suddenly it stopped working after password change. The window is stuck with a popup message which says 'Settings must have been crypto before synapse is activated'. Please help.

**Comment by techyogii** [comment]
Fixed the issue by resetting the brackets.json file.

**Comment by NM-19** [comment]
Hi techyogii, I have the same problem. How do I reset the brackets.json file?
Thanks
