### ISSUE TITLE
doesn't work on new Brackets version

### ISSUE THREAD

**Issue by nt-jjrubio** [kooohei/brackets-synapse#99]

**Comment by darknmy** [comment]
doesn't work on new Brackets version!

**Comment by MatthewMeredith** [comment]
Same here, just updated to Brackets 1.8 and now I can't connect to any of my projects... Making Brackets completely useless. Help!!!

**Comment by masumonline** [comment]
not working here too.

what a good extension. now a fail

**Comment by Emaxoso** [comment]
Anyone know if the author will fix this?

**Comment by darknmy** [comment]
I'm using latest Brackets + SSHFS Manager w/o plugin or Brackets editor freezing

**Comment by chrissabato** [comment]
Any update to this?

**Comment by MatthewMeredith** [comment]
Not that I've seen; I rolled back to Brackets 1.7 and everything works fine.

**Comment by kooohei** [comment]
Sorry I will fix to soon.
plz wait.

**Comment by mnishig** [comment]
Thaks for greate work!

reason of this issue seem like ssh2-streams about following link.
https://github.com/mscdex/ssh2-streams/pull/47

I modifiy synapse's private  at node/node_modules/ssh2-streams/lib/sftp.js
From
var constants = process.binding('constants');

TO
var constants = require('fs').constants || process.binding('constants');

I just run few times, but it works fine.

**Comment by kooohei** [comment]
thx for fix.
I could not courrespond the extension to new version cuz I don't have my time.

however module FTP, FTPS and SFTP is already done by golang and Javascript and few UI part.

**Comment by nabtron** [comment]
is it fixed?

**Comment by mnishig** [comment]
By workaroud,
This issue can fix realy simple patch to node/package.json
from
    "ssh2": "^0.4.11"
to
    "ssh2": "^0.5.4"

Try above!!
I'm waiting fixed release too.

**Comment by nabtron** [comment]
@mnishig can't find node/package.json , im using brackets 1.8 on Mac

**Comment by nabtron** [comment]
@mnishig thanks :) found it in extensions folder!

**Comment by nabtron** [comment]
@mnishig however, still not solved, keeps loading when click on "connect" and nothing happens.

**Comment by mnishig** [comment]
@nabtron ) I checked steps. ooops! After patch,  you should run npm install at node folder in synapse's extention foleder .

ex )
$ pwd
/Users/mnishi/Library/Application Support/Brackets/extensions/user/brackets-synapse/node
$ npm install 
- jsbn@0.1.0 node_modules/jsbn
- readable-stream@1.0.33 node_modules/ssh2-streams/node_modules/readable-stream
- readable-stream@1.0.33 node_modules/ssh2/node_modules/readable-stream
SynapseDomain@0.0.0 /Users/mnishi/Library/Application Support/Brackets/extensions/user/brackets-synapse/node
└─┬ ssh2@0.5.4 
  └─┬ ssh2-streams@0.1.16 
    └── semver@5.3.0

**Comment by nabtron** [comment]
@mnishig thanks buddy! working perfectly now!

**Comment by JustAGrumpyGuy** [comment]
Just upgraded to 1.9 build on Brackets

Had to use the step above from : mnishig 
for the system to work properly.

Location of file: 
C:\Users\xxxxxx\AppData\Roaming\Brackets\extensions\user\brackets-synapse\node\node_modules\ssh2-streams\lib\sftp.js

Was on line 9 for me, 

Should be:

 constants =  require('fs').constants || process.binding('constants'),

This resolved the issue where it just keeps looking, no progress or warnings.

**Comment by DrakeSeven** [comment]
@mnishig your **patch** followed by **npm install at node folder** worked!
Now SFTP works, Thanks!
&#x1F4D8; _Brackets 1.9 | npm -v 5.0.3 | MacOS Sierra_

**-bash**
```
Drake7$ cd /Users/Drake7/Library/Application\ Support/Brackets/extensions/user/brackets-synapse/node
Drake7$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN SynapseDomain@0.0.0 No description
npm WARN SynapseDomain@0.0.0 No repository field.

added 2 packages, removed 4 packages and updated 1 package in 2.337s
```
&#x1F34E; I didn't commit `package-lock.json`

**Comment by conspacer** [comment]
@RemembranceX your instruction worked perfect for Brackets on Windows 10 (64). 
Line 9 👍 
No need for updating anything else so far, works for key auth over SFTP.

**Comment by Ahmad1s** [comment]
I just used the solution mentioned above and changed line#9 in C:\Users\xxxxxxxx\AppData\Roaming\Brackets\extensions\user\brackets-synapse\node\node_modules\ssh2-streams\lib\sftp.js

to the below, and it worked like a magic
constants = require('fs').constants || process.binding('constants'),

Thanks @mnishig &  @RemembranceX

**Comment by BTSQL** [comment]
I also solved this problem on Ubuntu 
just replace code 
~/.config/Brackets/extensions/user/brackets-synapse/node/node_modules/ssh2-streams/lib$
vi sftp.js  (line 9)
constants = require('fs').constants || process.binding('constants'), 

Thanks @mnishig & @RemembranceX

**Comment by t36512** [comment]
I also fixed mine (release 1.11 on macOS High Sierra 10.13.6)
Made it with reference from @BTSQL 's comment so here it is:  

/Users/[username]/Library/Application Support/Brackets/extensions/user/brackets-synapse/node/node_modules/ssh2-streams/lib
vi sftp.js (line 9)
constants = require('fs').constants || process.binding('constants'),

Great thanks to the author and @BTSQL & @mnishig & @RemembranceX

**Comment by osalem** [comment]
Spending almost 90% of the past 48 hours ,, installing ubuntu ,, registering domains,, SSL + apache ,, coding reCaptcha v3.,, CSS,, breach compilations.
Ended up will Brackets not able to connect to my server ,, at some point there there is not enough words to express the gratitude,, but thank you all.. by the way ,, this is chineese for me.

I guess thing are easier in the field of security,, cheers and happy new year all.

**Comment by Abraham-Tourdex** [comment]
Just adding to the discussion, I'm on a mac - MacOS Yosemite 10.10.5

The above solution works - but the file was hard to find for me. I found it under 
`/Users/username/Library/Application Support/Brackets/extensions/user/brackets-synapse/node/node_modules/ssh2-streams`

BUT in order to access the `Library` folder, you need to open a Finder window, open the 'Go' menu in the bar at the top of the screen, then press alt (option) and you'll see the `Library` entry pop up.

Then once you have opened `sftp.js`, find the line that looks like this:
`constants = process.binding('constants'),`
and replace that variable definition with this:
`constants = require('fs').constants || process.binding('constants'),`

Worked for me and I just installed the latest brackets 1.13 build 1.13.0-17696 (release 49d29a8bc) yeyy
